import {NextResponse} from 'next/server';
import postgres from 'postgres';
export const runtime='nodejs'; export const maxDuration=45;

const allowed=['/dashboard','/admin','/fetch','/enquiries/tb-yb','/enquiries/franchise','/inspections/building-national','/inspections/building-franchise','/inspections/pool-national','/inspections/pool-franchise','/inspectors','/inspectors/dimitrios-moutsos','/inspectors/priya-nair','/inspectors/jordan-lee','/report-studio','/franchises','/franchises/melbourne-east','/franchises/geelong','/franchises/ballarat','/storage','/campaigns','/referrals','/referrals/revic214','/referrals/revic309','/reviews','/quick-sms','/field','/training','/access-control'];
const schema={type:'object',additionalProperties:false,properties:{message:{type:'string'},actions:{type:'array',maxItems:5,items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},label:{type:'string'},target:{type:'string',enum:allowed}},required:['id','label','target']}},drafts:{type:'array',maxItems:12,items:{type:'object',additionalProperties:false,properties:{entity:{type:'string',enum:['enquiry','inspection','report','franchise','inspector','referral','client']},field:{type:'string'},value:{type:['string','number','boolean','null']},confidence:{type:'number',minimum:0,maximum:1},reason:{type:'string'}},required:['entity','field','value','confidence','reason']}}},required:['message','actions','drafts']};
const stop=/\b(show|tell|find|open|about|client|customer|person|place|location|details|profile|please|what|where|who|from|inspectflow|inspection|the|this|that|and|for|with|me|any)\b/gi;
function fallback(message){const q=message.toLowerCase();let target=q.includes('report')?'/report-studio':q.includes('document')||q.includes('pdf')?'/fetch':q.includes('enquir')?'/enquiries/tb-yb':q.includes('inspector')?'/inspectors':q.includes('franchise')?'/franchises':q.includes('refer')?'/referrals':null;return {message:target?'I can open the relevant InspectFlow workspace.':'I can help with live operational context, records, reports, document intake and navigation.',actions:target?[{id:'open',label:'Open workspace',target}]:[],drafts:[],source:'deterministic'}}
async function callOpenRouter(apiKey,payload){return fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','HTTP-Referer':process.env.NEXT_PUBLIC_APP_URL||'https://inspectflow-ai-ops.vercel.app','X-Title':'InspectFlow'},body:JSON.stringify(payload),signal:AbortSignal.timeout(35000)})}
function needleFrom(message){return message.replace(stop,' ').replace(/[^a-zA-Z0-9@.+\-\s]/g,' ').replace(/\s+/g,' ').trim().slice(0,100)}
async function liveLookup(message){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL;if(!url)return [];const needle=needleFrom(message);if(needle.length<3)return [];const pattern=`%${needle}%`;let sql;try{sql=postgres(url,{max:1,connect_timeout:5,idle_timeout:2,ssl:'require'});const [enq,ins,people,fr,refs,places]=await Promise.all([
 sql`select 'enquiry' as kind,id::text,concat_ws(' ',client_first_name,client_last_name) as name,property_address as detail,status from enquiries where concat_ws(' ',client_first_name,client_last_name,client_email,client_mobile,property_address) ilike ${pattern} limit 4`,
 sql`select 'inspection' as kind,id::text,reference_number as name,concat_ws(' · ',client_first_name||' '||client_last_name,property_address) as detail,status from inspections where concat_ws(' ',reference_number,client_first_name,client_last_name,client_email,client_mobile,property_address) ilike ${pattern} limit 4`,
 sql`select 'inspector' as kind,id::text,name,concat_ws(' · ',email,phone) as detail,status from inspectors where concat_ws(' ',name,email,phone) ilike ${pattern} limit 4`,
 sql`select 'franchise' as kind,id::text,name,concat_ws(' · ',region,contact_name,contact_email,contact_phone) as detail,status from franchises where concat_ws(' ',name,region,contact_name,contact_email,contact_phone) ilike ${pattern} limit 4`,
 sql`select 'referral' as kind,id::text,name,concat_ws(' · ',agency,agent_code) as detail,'active' as status from referral_agents where concat_ws(' ',name,agency,agent_code) ilike ${pattern} limit 4`,
 sql`select 'location' as kind,id::text,place_name as name,concat_ws(' · ',address,phone,website) as detail,'listed' as status from google_locations where concat_ws(' ',place_name,address,phone,website) ilike ${pattern} limit 4`
 ]);return [...enq,...ins,...people,...fr,...refs,...places].slice(0,12)}catch(e){console.error('Assistant live lookup',e?.message||e);return []}finally{await sql?.end?.({timeout:1}).catch(()=>{})}}

export async function POST(req){try{const body=await req.json();const message=String(body.message||'').slice(0,8000);if(!message.trim())return NextResponse.json({error:'Message required'},{status:400});const apiKey=process.env.OPENROUTER_API_KEY;if(!apiKey)return NextResponse.json(fallback(message));const records=await liveLookup(message);const attachments=Array.isArray(body.attachments)?body.attachments.slice(0,8).map(a=>({name:String(a.name||''),type:String(a.type||''),summary:String(a.summary||'').slice(0,3000),fields:a.fields||{},transcript:String(a.transcript||'').slice(0,8000)})):[];const base={model:process.env.OPENROUTER_CHAT_MODEL||'openrouter/auto',temperature:.15,messages:[{role:'system',content:`You are InspectFlow Assistant, an operations copilot for a multi-tenant building and pool inspection platform. Use the provided live context, record lookup results and attachment extraction only. Be concise, practical and trainee-friendly. If the user asks about a named client, inspector, franchise, referral or place, prioritize matching live records. Never claim a write action was completed unless the application confirms it. Attachment-derived values must be returned as drafts, not silently treated as saved. Never return arbitrary URLs. Allowed targets: ${allowed.join(', ')}.`},{role:'system',content:`Current UI context: ${JSON.stringify(body.context||{})}`},{role:'system',content:`Matching database records: ${JSON.stringify(records)}`},{role:'system',content:`Attached file extraction: ${JSON.stringify(attachments)}`},{role:'user',content:message}]};let res=await callOpenRouter(apiKey,{...base,response_format:{type:'json_schema',json_schema:{name:'inspectflow_response',strict:true,schema}}});if(!res.ok)res=await callOpenRouter(apiKey,{...base,messages:[...base.messages,{role:'system',content:'Return JSON only with shape {"message":"...","actions":[{"id":"...","label":"...","target":"/allowed-path"}],"drafts":[{"entity":"enquiry","field":"property_address","value":"...","confidence":0.95,"reason":"..."}]}. No markdown.'}]});if(!res.ok){const text=await res.text();console.error('OpenRouter',res.status,text.slice(0,500));return NextResponse.json({...fallback(message),providerError:true,records})}const data=await res.json();let raw=data?.choices?.[0]?.message?.content;let parsed=typeof raw==='string'?JSON.parse(raw):raw;const actions=Array.isArray(parsed?.actions)?parsed.actions.filter(a=>allowed.includes(a.target)).slice(0,5):[];const drafts=Array.isArray(parsed?.drafts)?parsed.drafts.slice(0,12):[];return NextResponse.json({message:String(parsed?.message||'Ready.'),actions,drafts,records,source:'openrouter',model:data.model||base.model})}catch(e){console.error('AI route',e);return NextResponse.json({message:'The AI service is temporarily unavailable. InspectFlow remains usable.',actions:[],drafts:[],source:'fallback'},{status:200})}}
