'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {CalendarDays,ChevronDown,ChevronRight,Copy,CreditCard,FileText,MessageSquareText,RefreshCw,Search,SlidersHorizontal,Trash2,UserRoundCheck,X} from 'lucide-react';
import {inspections} from '../lib/data';

const tabs=[['building-national','Building · National'],['building-franchise','Building · Franchise'],['pool-national','Pool · National'],['pool-franchise','Pool · Franchise']];
const reports=['All','Submitted','Draft'];
const inspectorsList=['All',...Array.from(new Set(inspections.map(item=>item.inspector)))];

export default function InspectionsModule({slug=[]}){
 const view=slug[0]||'building-national';
 const [q,setQ]=useState(''),[range,setRange]=useState('3 Months'),[selected,setSelected]=useState(null),[modal,setModal]=useState(null),[rangeOpen,setRangeOpen]=useState(false),[filterOpen,setFilterOpen]=useState(false),[customRange,setCustomRange]=useState({from:'',to:''}),[reportFilter,setReportFilter]=useState('All'),[inspectorFilter,setInspectorFilter]=useState('All');
 const rows=useMemo(()=>inspections
  .filter(item=>JSON.stringify(item).toLowerCase().includes(q.toLowerCase()))
  .filter(item=>view.startsWith('pool')?item.type.includes('Pool'):!item.type.includes('Pool'))
  .filter(item=>reportFilter==='All'||item.report===reportFilter)
  .filter(item=>inspectorFilter==='All'||item.inspector===inspectorFilter)
  .filter(item=>withinRange(item.date,customRange)),[q,view,reportFilter,inspectorFilter,customRange]);
 const activeFilters=(reportFilter!=='All'?1:0)+(inspectorFilter!=='All'?1:0);
 const rangeLabel=customRange.from&&customRange.to?'Custom':range;
 return <div className="stack-lg inspections-page">
  <div className="page-heading"><div><p className="eyebrow">Bookings & reports</p><h1>Inspections</h1><p>{tabs.find(tab=>tab[0]===view)?.[1]} · {rows.length} records</p></div><button className="button secondary" type="button" onClick={()=>location.reload()}><RefreshCw size={15}/>Refresh</button></div>
  <div className="module-tabs scroll-tabs" role="tablist">{tabs.map(([id,label])=><Link role="tab" aria-selected={view===id} className={view===id?'active':''} href={`/inspections/${id}`} key={id}>{label}</Link>)}</div>
  <section className="surface compact-toolbar">
   <label className="search-field"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search client, reference, inspector or address"/></label>
   <div className="preset-row">{['1 Week','3 Months','1 Year'].map(p=><button className={range===p&&!customRange.from?'active':''} type="button" onClick={()=>{setRange(p);setCustomRange({from:'',to:''})}} key={p}>{p}</button>)}</div>
   <div className="toolbar-popover-wrap"><button type="button" className={`button secondary ${rangeOpen?'active-control':''}`} aria-haspopup="dialog" aria-expanded={rangeOpen} onClick={()=>{setRangeOpen(v=>!v);setFilterOpen(false)}}><CalendarDays size={15}/>{rangeLabel}<ChevronDown size={13}/></button>{rangeOpen&&<DateRangePopover value={customRange} onChange={setCustomRange} close={()=>setRangeOpen(false)} reset={()=>{setCustomRange({from:'',to:''});setRange('3 Months')}}/>}</div>
   <div className="toolbar-popover-wrap"><button type="button" className={`button secondary ${filterOpen||activeFilters?'active-control':''}`} aria-haspopup="dialog" aria-expanded={filterOpen} onClick={()=>{setFilterOpen(v=>!v);setRangeOpen(false)}}><SlidersHorizontal size={15}/>Filters{activeFilters?<span className="filter-count">{activeFilters}</span>:null}</button>{filterOpen&&<div className="filter-menu filter-form" role="dialog" aria-label="Inspection filters"><label>Report status<select value={reportFilter} onChange={e=>setReportFilter(e.target.value)}>{reports.map(value=><option key={value}>{value}</option>)}</select></label><label>Inspector<select value={inspectorFilter} onChange={e=>setInspectorFilter(e.target.value)}>{inspectorsList.map(value=><option key={value}>{value}</option>)}</select></label><div className="popover-actions"><button type="button" className="button secondary" onClick={()=>{setReportFilter('All');setInspectorFilter('All')}}>Reset</button><button type="button" className="button primary" onClick={()=>setFilterOpen(false)}>Apply filters</button></div></div>}</div>
   <span className="result-count">{rows.length} jobs</span>
  </section>
  <section className="surface inspection-table"><div className="inspection-head"><span>Client / reference</span><span>Schedule</span><span>Financials</span><span>Inspection</span><span>Inspector</span><span>Report</span><span></span></div>{rows.map(item=>{const due=Math.max(0,item.price-item.paid);return <button type="button" className="inspection-row" key={item.id} onClick={()=>setSelected(item)}><span><b>{item.name}</b><small>{item.id}</small></span><span><b>{item.date}</b><small>{item.time}</small></span><span><b>${item.price}</b><small>Paid ${item.paid} · Due ${due}</small></span><span><em className={`status ${slugify(item.status)}`}>{item.status}</em><small>{item.type}</small></span><span><b>{item.inspector}</b><small>{item.franchise}</small></span><span><em className={`status ${item.report==='Submitted'?'booked':'follow-up'}`}>{item.report}</em><small>{item.report==='Submitted'?'PDF available':'Draft'}</small></span><ChevronRight size={15}/></button>})}</section>
  {selected&&<div className="side-sheet-layer" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="detail-sheet inspection-detail" aria-label={`Inspection ${selected.id}`}><header><div><small>{selected.id}</small><h2>{selected.name}</h2></div><button type="button" aria-label="Close inspection details" onClick={()=>setSelected(null)}><X size={17}/></button></header><div className="detail-body"><div className="detail-grid"><span><small>Status</small><b>{selected.status}</b></span><span><small>Inspector</small><b>{selected.inspector}</b></span><span><small>Scheduled</small><b>{selected.date} · {selected.time}</b></span><span><small>Balance</small><b>${Math.max(0,selected.price-selected.paid)}</b></span></div><div className="detail-block"><small>Property</small><p>{selected.address}</p></div><div className="action-grid"><button type="button" onClick={()=>setModal({type:'assign'})}><UserRoundCheck size={15}/>Inspector</button><button type="button" onClick={()=>setModal({type:'payment'})}><CreditCard size={15}/>Payments</button><Link href="/report-studio"><FileText size={15}/>Report</Link><button type="button"><MessageSquareText size={15}/>SMS</button><button type="button" onClick={()=>navigator.clipboard?.writeText(selected.id)}><Copy size={15}/>Copy reference</button><button className="danger-action" type="button" onClick={()=>setModal({type:'destructive'})}><Trash2 size={15}/>Cancel / Delete</button></div></div></aside></div>}
  {modal&&selected&&<InspectionModal modal={modal} record={selected} close={()=>setModal(null)}/>} 
 </div>
}

function DateRangePopover({value,onChange,close,reset}){return <div className="range-popover" role="dialog" aria-label="Custom date range"><div className="range-fields"><label>From<input type="date" value={value.from} onChange={e=>onChange({...value,from:e.target.value})}/></label><label>To<input type="date" value={value.to} min={value.from||undefined} onChange={e=>onChange({...value,to:e.target.value})}/></label></div><div className="popover-actions"><button type="button" className="button secondary" onClick={()=>{reset();close()}}>Reset</button><button type="button" className="button primary" disabled={!value.from||!value.to} onClick={close}>Apply range</button></div></div>}

function InspectionModal({modal,record,close}){const [choice,setChoice]=useState('');return <div className="modal-layer" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-card" role="dialog" aria-modal="true" aria-label={modal.type==='assign'?'Assign inspector':modal.type==='payment'?'Payments':'Cancel or delete inspection'}><header><div><small>{record.id}</small><h2>{modal.type==='assign'?'Assign inspector':modal.type==='payment'?'Payments':'Cancel or delete'}</h2></div><button type="button" aria-label="Close" onClick={close}><X size={17}/></button></header><div className="modal-body">{modal.type==='assign'?<div className="form-grid single"><label>Inspector<select defaultValue={record.inspector}><option>{record.inspector}</option><option>Dimitrios Moutsos</option><option>Priya Nair</option><option>Jordan Lee</option></select></label><label className="check-line"><input type="checkbox" defaultChecked/>Send inspector notification</label><label className="check-line"><input type="checkbox" defaultChecked/>Send client notification</label></div>:modal.type==='payment'?<><div className="payment-summary"><span><small>Total</small><b>${record.price}</b></span><span><small>Paid</small><b>${record.paid}</b></span><span><small>Due</small><b>${Math.max(0,record.price-record.paid)}</b></span></div><div className="form-grid"><label>Method<select><option>Paid Online</option><option>BPay</option><option>NabTransact</option><option>Cash</option></select></label><label>Date<input type="date"/></label><label>Receipt number<input/></label><label>Amount<input type="number"/></label></div></>:<div className="destructive-choice"><button type="button" aria-pressed={choice==='cancel'} className={`cancel-choice ${choice==='cancel'?'selected':''}`} onClick={()=>setChoice('cancel')}><b>Cancel inspection</b><span>Keeps this record, payment history and audit trail. Use when the booking should no longer proceed.</span></button><button type="button" aria-pressed={choice==='delete'} className={`delete-choice ${choice==='delete'?'selected':''}`} onClick={()=>setChoice('delete')}><b>Delete permanently</b><span>Removes this record after elevated confirmation. Limit this to duplicates or invalid records.</span></button></div>}</div><footer><button className="button secondary" onClick={close}>Close</button><button className="button primary" disabled={modal.type==='destructive'&&!choice} onClick={close}>{modal.type==='assign'?'Assign & notify':modal.type==='payment'?'Add payment':choice==='delete'?'Confirm deletion':'Confirm cancellation'}</button></footer></div></div>}

function withinRange(dateLabel,range){if(!range.from||!range.to)return true;const months={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};const [day,month,year]=dateLabel.split(' ');const date=new Date(Number(year),months[month],Number(day));const from=new Date(`${range.from}T00:00:00`);const to=new Date(`${range.to}T23:59:59`);return date>=from&&date<=to}
function slugify(v=''){return v.toLowerCase().replaceAll(' ','-')}
