'use client';
import Link from 'next/link';
import {useEffect} from 'react';
import {ArrowRight,Building2,CheckCircle2,ClipboardCheck,FileText,MapPin,ShieldCheck,Smartphone,Users} from 'lucide-react';

export default function LandingPage(){
 useEffect(()=>{const nodes=[...document.querySelectorAll('[data-reveal]')];if(!('IntersectionObserver'in window)){nodes.forEach(n=>n.dataset.visible='true');return}const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.dataset.visible='true';observer.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -7%'});nodes.forEach(n=>observer.observe(n));return()=>observer.disconnect()},[]);
 return <main className="if-landing">
  <nav className="landing-nav" aria-label="Public navigation"><Link href="/" className="landing-brand"><span>IF</span><b>InspectFlow</b></Link><div><a href="#platform">Platform</a><a href="#roles">Roles</a><a href="#field">Field</a><a href="#reports">Reports</a></div><Link className="landing-nav-cta" href="/dashboard">Open console <ArrowRight size={14}/></Link></nav>
  <section className="landing-hero" data-reveal><div className="landing-hero-copy"><p className="landing-kicker">Inspection operations, connected end to end</p><h1>From first enquiry<br/>to issued report.</h1><p>InspectFlow coordinates clients, franchises, inspectors, field evidence, document intake, reporting and operational follow-up from one controlled workspace.</p><div className="landing-actions"><Link href="/dashboard">Open InspectFlow <ArrowRight size={15}/></Link><Link href="/report-studio">Explore Report Studio</Link></div><div className="landing-proof"><span><ShieldCheck size={14}/>Role-aware operations</span><span><Smartphone size={14}/>PWA field workflow</span><span><CheckCircle2 size={14}/>Accessible by design</span></div></div><div className="landing-hero-visual" aria-label="InspectFlow operational preview"><div className="landing-float-card float-a"><small>Today</small><b>12 inspections</b><span>3 reports awaiting issue</span></div><div className="landing-console-frame"><header><span>IF</span><i/><i/><i/></header><div className="landing-console-body"><aside><i/><i/><i/><i/><i/></aside><section><div className="landing-console-title"><small>Operations overview</small><b>Inspection activity</b></div><div className="landing-console-bars">{[38,62,51,78,68,86,73,92,64,82].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><div className="landing-console-list"><span/><span/><span/></div></section></div></div><div className="landing-float-card float-b"><small>Report QA</small><b>98% ready</b><span>Evidence linked · sign-off present</span></div></div></section>

  <section className="landing-signal" aria-label="Platform capabilities">{[['Enquiries','Client intake and qualification'],['Inspections','Assignment and field delivery'],['Report Studio','Four issue-ready report systems'],['Network','Franchise and referral control']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section>

  <section id="platform" className="landing-section landing-platform" data-reveal><header className="landing-section-head"><p>One operational system</p><h2>Less handoff. More control.</h2><span>Every workflow stays linked to the client, property, inspection and responsible team.</span></header><div className="landing-feature-rows"><article><span><Users size={18}/></span><div><small>01 · Lead management</small><h3>Enquiries become structured inspection work.</h3><p>Capture contact, access, property, referral and booking details without losing context between teams.</p></div><b>Client → property → booking</b></article><article><span><ClipboardCheck size={18}/></span><div><small>02 · Delivery</small><h3>Inspectors see the work they can act on.</h3><p>Assignments, availability, evidence, inspection types and field status remain connected to operational scope.</p></div><b>Schedule → field → QA</b></article><article><span><FileText size={18}/></span><div><small>03 · Reporting</small><h3>Issue reports with evidence and decisions intact.</h3><p>Executive, Technical, Editorial and Compact templates share the same inspection record without collapsing into one visual treatment.</p></div><b>Evidence → report → client</b></article></div></section>

  <section id="roles" className="landing-section landing-dark" data-reveal><div className="landing-role-copy"><p>Role-aware by structure</p><h2>The right surface for every person in the workflow.</h2><span>Super admins govern the platform. Admins control organizations. Employees coordinate work. Inspectors deliver field records. Clients access their outcomes. Trainees learn through constrained workflows.</span></div><div className="landing-role-list">{[['Super Admin','Platform, tenants, security and permissions'],['Admin','Organization, franchise and workforce control'],['Employee','Enquiries, inspections, reporting and client operations'],['Inspector','Assigned field work, evidence and reports'],['Client','Own inspections, documents and reports'],['Trainee','Guided training with supervised access']].map((r,i)=><div key={r[0]}><small>{String(i+1).padStart(2,'0')}</small><b>{r[0]}</b><span>{r[1]}</span></div>)}</div></section>

  <section id="field" className="landing-section landing-field" data-reveal><div className="landing-phone" aria-hidden="true"><div className="landing-phone-screen"><header><span>09:41</span><b>IF</b></header><main><small>Next inspection</small><h3>51 Trisha Drive</h3><p>Building & Pest · 09:00</p><div className="phone-step active"><i/>Arrival & access</div><div className="phone-step"><i/>Exterior</div><div className="phone-step"><i/>Interior</div><div className="phone-step"><i/>Roof & sub-floor</div><button>Continue inspection</button></main></div></div><div className="landing-field-copy"><p>Field-first PWA</p><h2>Built for the property, not the desk.</h2><p>Inspectors can move through assigned work with touch-ready controls, structured evidence capture, offline-conscious PWA behavior and clear progress states.</p><ul><li><Smartphone size={15}/>Mobile-first inspection flow</li><li><MapPin size={15}/>Location and property context</li><li><ShieldCheck size={15}/>Role-constrained actions</li></ul><Link href="/field">Open Field App <ArrowRight size={14}/></Link></div></section>

  <section id="reports" className="landing-section landing-reports" data-reveal><header className="landing-section-head"><p>Report Studio</p><h2>Different clients need genuinely different documents.</h2><span>Choose the report structure that fits the inspection and audience without changing the underlying source record.</span></header><div className="landing-report-grid">{[['Executive','Forest / Sand','Decision-first client summary'],['Technical','Blueprint / Ice','Evidence-dense compliance record'],['Editorial','Clay / Parchment','Image-led narrative document'],['Compact','Graphite / Mint','Fast-reading print-efficient report']].map((t,i)=><Link href={`/reports/IF-20841/preview?template=${t[0].toLowerCase()}`} key={t[0]}><div className={`landing-report-paper report-${i}`}><i/><i/><i/><i/></div><small>{t[1]}</small><b>{t[0]}</b><span>{t[2]}</span></Link>)}</div></section>

  <section className="landing-section landing-network" data-reveal><div><Building2 size={20}/><p>Franchise network</p><h2>Operate nationally without flattening local responsibility.</h2></div><div className="landing-network-lines"><span>Head Office</span><i/><span>Franchise</span><i/><span>Inspector</span><i/><span>Client</span></div><Link href="/franchises">Explore network workspace <ArrowRight size={14}/></Link></section>

  <section className="landing-final" data-reveal><p>InspectFlow Operations</p><h2>One controlled flow from enquiry to evidence to report.</h2><div><Link href="/dashboard">Enter dashboard <ArrowRight size={15}/></Link><Link href="/report-studio">Open Report Studio</Link></div></section>
  <footer className="landing-footer"><Link href="/" className="landing-brand"><span>IF</span><b>InspectFlow</b></Link><p>Inspection operations, field workflows, reporting and administration.</p><span>© 2026 InspectFlow</span></footer>
 </main>
}
