'use client';
import {useMemo} from 'react';
import {ArrowUpRight,CalendarDays,FileText,Inbox,RefreshCw,TriangleAlert} from 'lucide-react';
import {enquiries,inspections} from '../lib/data';
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n);
export default function Dashboard({admin=false}){
 const revenue=useMemo(()=>inspections.reduce((s,x)=>s+x.price,0),[]);
 const kpis=[['New enquiries today','1',Inbox,'blue'],['Completed this month','1',FileText,'green'],['Upcoming inspections','4',CalendarDays,'amber'],['Reports pending','3',TriangleAlert,'red']];
 return <div className="stack-lg"><div className="page-heading"><div><p className="eyebrow">{admin?'Administration':'Operations overview'}</p><h1>{admin?'Admin Console':'Dashboard'}</h1><p>Wednesday, 29 July 2026 · All Franchises</p></div><div className="heading-actions"><button className="button secondary" type="button"><RefreshCw size={15}/>Refresh</button><button className="button primary" type="button" onClick={()=>location.assign('/fetch')}><FileText size={15}/>Import document</button></div></div>
 <section className="kpi-grid">{kpis.map(([label,value,Icon,tone])=><article className={`surface kpi-card ${tone}`} key={label}><div><small>{label}</small><strong>{value}</strong><span>{label.includes('Upcoming')?'2 scheduled tomorrow':'Network-wide scope'}</span></div><Icon size={18}/></article>)}</section>
 <section className="dashboard-split"><article className="surface"><header className="section-head"><div><strong>Needs attention</strong><small>Only exceptions requiring human action</small></div><span className="count-pill">4</span></header><div className="attention-list">{[['High','Inspection tomorrow has no inspector','IF-20942 · 18 Peterhead Road'],['High','Access confirmation is missing','Olivia Hart · scheduled 13:30 PM'],['Medium','Outstanding balance','IF-20835 · A$842 due'],['Low','Report photo needs a caption','IF-20841 · Kitchen photo 04']].map((x,i)=><button type="button" key={i}><span className={`severity ${x[0].toLowerCase()}`}>{x[0]}</span><span><b>{x[1]}</b><small>{x[2]}</small></span><ArrowUpRight size={14}/></button>)}</div></article>
 <article className="surface metrics-card"><header className="section-head"><div><strong>Monthly performance</strong><small>Current network scope</small></div></header><div className="metric-grid"><div><small>Revenue</small><strong>{money(revenue)}</strong><span>54.7% of target</span></div><div><small>Conversion</small><strong>25.0%</strong><span>Enquiry to booking</span></div><div><small>Review rating</small><strong>4.8 ★</strong><span>460 total reviews</span></div></div></article></section>
 <section className="dashboard-grid"><article className="surface"><header className="section-head"><div><strong>Recent enquiries</strong><small>Latest in the current franchise scope</small></div><a href="/enquiries/tb-yb">View all</a></header><div className="compact-list">{enquiries.map(e=><a key={e.id} href="/enquiries/tb-yb"><span className="avatar">{e.name.split(' ').map(x=>x[0]).join('')}</span><span><b>{e.name}</b><small>{e.address}</small></span><span className={`status ${e.status.toLowerCase().replaceAll(' ','-')}`}>{e.status}</span></a>)}</div></article>
 <article className="surface"><header className="section-head"><div><strong>Upcoming inspections</strong><small>Next scheduled jobs</small></div><a href="/inspections/building-national">Open schedule</a></header><div className="compact-list">{inspections.map(i=><a key={i.id} href="/inspections/building-national"><span className="time-block"><b>{i.time}</b><small>{i.date.split(' ')[0]} Jul</small></span><span><b>{i.type}</b><small>{i.address}</small></span><span className={`status ${i.status==='Report Ready'?'booked':'follow-up'}`}>{i.status}</span></a>)}</div></article>
 <article className="surface calendar-card"><header className="section-head"><div><strong>July 2026</strong><small>Job days are marked</small></div></header><div className="calendar-grid">{['M','T','W','T','F','S','S'].map((d,i)=><b key={i}>{d}</b>)}{Array.from({length:31},(_,i)=>i+1).map(d=><span className={[23,29,30].includes(d)?'has-job':''} key={d}>{d}</span>)}</div></article></section></div>
}
