'use client';
import {useState} from 'react';
import {BadgeCheck,Copy,Download,FileText,Folder,Globe2,Mail,MapPin,MoreHorizontal,Plus,Search,Settings2,Upload} from 'lucide-react';

const inspectors=[{name:'Dimitrios Moutsos',phone:'0473 890 649',email:'dimitrios@inspectflow.au',works:'Melbourne East',types:['Building & Pest','Timber Pest','New Build'],owner:true},{name:'Priya Nair',phone:'0411 330 804',email:'priya@inspectflow.au',works:'Mornington Peninsula · Geelong',types:['Pool Barrier','Pre-Sale'],owner:false},{name:'Jordan Lee',phone:'0432 808 117',email:'jordan@inspectflow.au',works:'Bendigo · Ballarat',types:['Building','Dilapidation','Rental Standards'],owner:false}];
const franchises=[['F018','Melbourne East','Dimitrios Moutsos','Rowville VIC','Settlement','east@inspectflow.au','03 9000 1177'],['F024','Geelong','Oliver Grant','Geelong VIC','50-50 Contract','geelong@inspectflow.au','03 5200 8812'],['F031','Ballarat','Jordan Ross','Ballarat VIC','Foundation','ballarat@inspectflow.au','03 5300 2211']];

export default function NetworkModule({module}){if(module==='inspectors')return <Inspectors/>;if(module==='franchises')return <Franchises/>;if(module==='storage')return <Storage/>;if(module==='campaigns')return <Campaigns/>;if(module==='referrals')return <Referrals/>;if(module==='reviews')return <Reviews/>;return null}
function Shell({eyebrow,title,subtitle,action,children}){return <div className="stack-lg"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>{children}</div>}
function SearchBar({placeholder='Search'}){return <section className="surface compact-toolbar"><label className="search-field"><Search size={15}/><input placeholder={placeholder}/></label><span className="result-count">Current network scope</span></section>}

function Inspectors(){const [menu,setMenu]=useState(null);const copy=value=>navigator.clipboard?.writeText(value);return <Shell eyebrow="Workforce" title="Inspectors" subtitle="Credentials, availability, specialities and franchise coverage." action={<button className="button primary"><Plus size={15}/>Add inspector</button>}><SearchBar placeholder="Search inspectors"/><section className="surface people-table"><div className="people-head"><span>Inspector</span><span>Contact</span><span>Works for</span><span>Inspection types</span><span>Actions</span></div>{inspectors.map(person=><div className="people-row" key={person.name}><span><i className="avatar">{person.name.split(' ').map(part=>part[0]).join('').slice(0,2)}</i><span><b>{person.name}</b>{person.owner&&<small>Franchise Owner</small>}</span></span><span><b>{person.phone}</b><small>{person.email}</small></span><span>{person.works}</span><span className="tag-list">{person.types.map(type=><em key={type}>{type}</em>)}</span><span className="row-menu-wrap"><button type="button" className="round-action" data-tip="Inspector actions" aria-label={`Actions for ${person.name}`} aria-haspopup="menu" aria-expanded={menu===person.email} onClick={()=>setMenu(menu===person.email?null:person.email)}><MoreHorizontal size={15}/></button>{menu===person.email&&<div className="row-menu align-right" role="menu"><button type="button" role="menuitem" onClick={()=>{copy(person.email);setMenu(null)}}><Copy size={14}/>Copy email</button><a role="menuitem" href={`mailto:${person.email}`} onClick={()=>setMenu(null)}><Mail size={14}/>Email inspector</a><button type="button" role="menuitem" onClick={()=>location.assign('/admin')}><FileText size={14}/>Open admin record</button></div>}</span></div>)}</section></Shell>}

function Franchises(){return <Shell eyebrow="Network" title="Franchises" subtitle="Location ownership, contracts, invoicing and public microsites." action={<button className="button primary"><Plus size={15}/>Add franchise</button>}><SearchBar placeholder="Search franchise, owner, suburb or state"/><section className="surface people-table franchise-table"><div className="people-head"><span>Location</span><span>Owner</span><span>Region</span><span>Contract</span><span>Contact</span><span></span></div>{franchises.map(franchise=><div className="people-row" key={franchise[0]}><span><small>{franchise[0]}</small><b>{franchise[1]}</b></span><span>{franchise[2]}</span><span>{franchise[3]}</span><span><em className="soft-tag">{franchise[4]}</em></span><span><b>{franchise[5]}</b><small>{franchise[6]}</small></span><button type="button" className="round-action" data-tip="Open franchise settings" aria-label={`Open settings for ${franchise[1]}`} onClick={()=>location.assign('/admin')}><Settings2 size={14}/></button></div>)}</section></Shell>}

function Storage(){return <Shell eyebrow="Shared documents" title="Storage" subtitle="Versioned contracts, insurance, marketing and training files." action={<button className="button primary" onClick={()=>location.assign('/fetch')}><Upload size={15}/>Upload document</button>}><section className="surface storage-browser"><div className="storage-head"><span>Name</span><span>Version</span><span>Updated</span><span></span></div>{[['Documents / Contracts','v12','28 Jul 2026'],['Documents / Insurance','v8','18 Jul 2026'],['Documents / Templates','v23','27 Jul 2026'],['Marketing','v41','25 Jul 2026'],['Training','v18','11 Jul 2026']].map(row=><div className="storage-row" key={row[0]}><span><Folder size={16}/><b>{row[0]}</b></span><span>{row[1]}</span><span>{row[2]}</span><button type="button" data-tip="Download" aria-label={`Download ${row[0]}`}><Download size={14}/></button></div>)}<footer><span>3.2 GB of 10 GB used</span><div className="storage-progress"><i/></div></footer></section></Shell>}

function Campaigns(){return <Shell eyebrow="Email marketing" title="Campaigns" subtitle="Audience delivery with operational metrics, not decorative analytics." action={<button className="button primary"><Plus size={15}/>New campaign</button>}><div className="stat-strip"><span><small>Emails sent</small><b>24,180</b></span><span><small>Total recipients</small><b>19,406</b></span><span><small>Unsubscribes</small><b>88</b></span></div><div className="campaign-grid">{[['Winter Property Checklist','Past clients · All franchises','Sent','9,420','98.4%'],['Pool Compliance Reminder','Pool clients · Metro region','Sent','5,680','97.9%'],['Spring Agent Partner Pack','Referral agents · National','Draft','3,140','Draft']].map(campaign=><article className="surface campaign-card" key={campaign[0]}><header><div><small>{campaign[1]}</small><h3>{campaign[0]}</h3></div><em className={`status ${campaign[2].toLowerCase()}`}>{campaign[2]}</em></header><div><span><small>Delivered</small><b>{campaign[3]}</b></span><span><small>Rate</small><b>{campaign[4]}</b></span></div><div className="campaign-progress"><i style={{width:campaign[2]==='Draft'?'35%':campaign[4]}}/></div></article>)}</div></Shell>}

function Referrals(){const [tab,setTab]=useState('Agents');return <Shell eyebrow="Partner network" title="Referrals" subtitle="Referral agents, inspector sources and settlement ledgers." action={<button className="button primary"><Plus size={15}/>Add new agent</button>}><div className="module-tabs">{['Agents','Inspectors','All Bookings'].map(value=><button type="button" className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}>{value}</button>)}</div><section className="surface people-table"><div className="people-head"><span>Partner</span><span>Agency / source</span><span>Agent ID</span><span>Bookings</span><span>Referral total</span></div>{[['Grace Wilson','North & Co Realty','REVIC214','43','$6,450'],['Ethan Clark','Bayview Property','REVIC309','28','$4,180']].map(row=><div className="people-row" key={row[2]}><span><b>{row[0]}</b><small>{tab}</small></span><span>{row[1]}</span><span><em className="soft-tag">{row[2]}</em></span><span>{row[3]}</span><span>{row[4]}</span></div>)}</section></Shell>}

function Reviews(){const copy=value=>navigator.clipboard?.writeText(value);return <Shell eyebrow="Reputation" title="Reviews / Locations" subtitle="Location-level review health and recent client feedback."><div className="stat-strip"><span><small>Average rating</small><b>4.82 / 5</b></span><span><small>Total reviews</small><b>1,294</b></span><span><small>Locations</small><b>14</b></span></div><div className="review-grid">{[['Melbourne East','120 Collins St, Melbourne','4.9','282'],['Geelong','18 Moorabool St, Geelong','4.8','194']].map(row=>{const search=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`InspectFlow ${row[0]}`)}`;return <article className="surface location-card" key={row[0]}><header><div><h3>{row[0]}</h3><small><MapPin size={12}/>{row[1]}</small></div><b><BadgeCheck size={14}/>{row[2]} / 5</b></header><p>{row[3]} reviews</p><div className="rating-bars">{[92,6,2,0,0].map((value,index)=><div key={index}><span>{5-index}/5</span><i><b style={{width:`${value}%`}}/></i></div>)}</div><footer><a className="button secondary" href={search} target="_blank" rel="noreferrer"><Globe2 size={14}/>View on Google</a><button type="button" className="button secondary" onClick={()=>copy(search)}><Copy size={14}/>Copy review link</button></footer></article>})}</div></Shell>}
