'use client';
import {useState} from 'react';
import {Camera,ChevronRight,Download,FileText,Folder,Globe2,Mail,MapPin,MoreHorizontal,Plus,Search,Settings2,Star,Upload,Users} from 'lucide-react';
const inspectors=[{name:'Dimitrios Moutsos',phone:'0473 890 649',email:'dimitrios@inspectflow.au',works:'Melbourne East',types:['Building & Pest','Timber Pest','New Build'],owner:true},{name:'Priya Nair',phone:'0411 330 804',email:'priya@inspectflow.au',works:'Mornington Peninsula · Geelong',types:['Pool Barrier','Pre-Sale'],owner:false},{name:'Jordan Lee',phone:'0432 808 117',email:'jordan@inspectflow.au',works:'Bendigo · Ballarat',types:['Building','Dilapidation','Rental Standards'],owner:false}];
const franchises=[['F018','Melbourne East','Dimitrios Moutsos','Rowville VIC','Settlement','east@inspectflow.au','03 9000 1177'],['F024','Geelong','Oliver Grant','Geelong VIC','50-50 Contract','geelong@inspectflow.au','03 5200 8812'],['F031','Ballarat','Jordan Ross','Ballarat VIC','Foundation','ballarat@inspectflow.au','03 5300 2211']];
export default function NetworkModule({module}){if(module==='inspectors')return <Inspectors/>;if(module==='franchises')return <Franchises/>;if(module==='storage')return <Storage/>;if(module==='campaigns')return <Campaigns/>;if(module==='referrals')return <Referrals/>;if(module==='reviews')return <Reviews/>;return null}
function Shell({eyebrow,title,subtitle,action,children}){return <div className="stack-lg"><div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>{children}</div>}
function SearchBar({placeholder='Search'}){return <section className="surface compact-toolbar"><label className="search-field"><Search size={15}/><input placeholder={placeholder}/></label><span className="result-count">Current network scope</span></section>}
function Inspectors(){return <Shell eyebrow="Workforce" title="Inspectors" subtitle="Credentials, availability, specialities and franchise coverage." action={<button className="button primary"><Plus size={15}/>Add inspector</button>}><SearchBar placeholder="Search inspectors"/><section className="surface people-table"><div className="people-head"><span>Inspector</span><span>Contact</span><span>Works for</span><span>Inspection types</span><span>Actions</span></div>{inspectors.map(p=><div className="people-row" key={p.name}><span><i className="avatar">{p.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</i><span><b>{p.name}</b>{p.owner&&<small>Franchise Owner</small>}</span></span><span><b>{p.phone}</b><small>{p.email}</small></span><span>{p.works}</span><span className="tag-list">{p.types.map(x=><em key={x}>{x}</em>)}</span><span className="icon-actions"><button data-tip="Edit inspector"><Settings2 size={14}/></button><button data-tip="Profile photo"><Camera size={14}/></button><button data-tip="Bio & credentials"><FileText size={14}/></button></span></div>)}</section></Shell>}
function Franchises(){return <Shell eyebrow="Network" title="Franchises" subtitle="Location ownership, contracts, invoicing and public microsites." action={<button className="button primary"><Plus size={15}/>Add franchise</button>}><SearchBar placeholder="Search franchise, owner, suburb or state"/><section className="surface people-table franchise-table"><div className="people-head"><span>Location</span><span>Owner</span><span>Region</span><span>Contract</span><span>Contact</span><span></span></div>{franchises.map(f=><div className="people-row" key={f[0]}><span><small>{f[0]}</small><b>{f[1]}</b></span><span>{f[2]}</span><span>{f[3]}</span><span><em className="soft-tag">{f[4]}</em></span><span><b>{f[5]}</b><small>{f[6]}</small></span><button className="round-action" data-tip="Franchise settings"><Settings2 size={14}/></button></div>)}</section></Shell>}
function Storage(){return <Shell eyebrow="Shared documents" title="Storage" subtitle="Versioned contracts, insurance, marketing and training files." action={<div className="heading-actions"><button className="button secondary"><Folder size={15}/>New folder</button><button className="button primary"><Upload size={15}/>Upload</button></div>}><section className="surface storage-browser"><div className="storage-head"><span>Name</span><span>Version</span><span>Updated</span><span></span></div>{[['Documents / Contracts','v12','28 Jul 2026'],['Documents / Insurance','v8','18 Jul 2026'],['Documents / Templates','v23','27 Jul 2026'],['Marketing','v41','25 Jul 2026'],['Training','v18','11 Jul 2026']].map(x=><div className="storage-row" key={x[0]}><span><Folder size={16}/><b>{x[0]}</b></span><span>{x[1]}</span><span>{x[2]}</span><button data-tip="Download"><Download size={14}/></button></div>)}<footer><span>3.2 GB of 10 GB used</span><div className="storage-progress"><i/></div></footer></section></Shell>}
function Campaigns(){return <Shell eyebrow="Email marketing" title="Campaigns" subtitle="Audience delivery with operational metrics, not decorative analytics." action={<button className="button primary"><Plus size={15}/>New campaign</button>}><div className="stat-strip"><span><small>Emails sent</small><b>24,180</b></span><span><small>Total recipients</small><b>19,406</b></span><span><small>Unsubscribes</small><b>88</b></span></div><div className="campaign-grid">{[['Winter Property Checklist','Past clients · All franchises','Sent','9,420','98.4%'],['Pool Compliance Reminder','Pool clients · Metro region','Sent','5,680','97.9%'],['Spring Agent Partner Pack','Referral agents · National','Draft','3,140','Draft']].map(c=><article className="surface campaign-card" key={c[0]}><header><div><small>{c[1]}</small><h3>{c[0]}</h3></div><em className={`status ${c[2].toLowerCase()}`}>{c[2]}</em></header><div><span><small>Delivered</small><b>{c[3]}</b></span><span><small>Rate</small><b>{c[4]}</b></span></div><div className="campaign-progress"><i style={{width:c[2]==='Draft'?'35%':c[4]}}/></div></article>)}</div></Shell>}
function Referrals(){const [tab,setTab]=useState('Agents');return <Shell eyebrow="Partner network" title="Referrals" subtitle="Referral agents, inspector sources and settlement ledgers." action={<button className="button primary"><Plus size={15}/>Add new agent</button>}><div className="module-tabs">{['Agents','Inspectors','All Bookings'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><section className="surface people-table"><div className="people-head"><span>Partner</span><span>Agency / source</span><span>Agent ID</span><span>Bookings</span><span>Referral total</span></div>{[['Grace Wilson','North & Co Realty','REVIC214','43','$6,450'],['Ethan Clark','Bayview Property','REVIC309','28','$4,180']].map(r=><div className="people-row" key={r[2]}><span><b>{r[0]}</b><small>{tab}</small></span><span>{r[1]}</span><span><em className="soft-tag">{r[2]}</em></span><span>{r[3]}</span><span>{r[4]}</span></div>)}</section></Shell>}
function Reviews(){return <Shell eyebrow="Reputation" title="Reviews / Locations" subtitle="Location-level review health and recent client feedback."><div className="stat-strip"><span><small>Average rating</small><b>4.82 ★</b></span><span><small>Total reviews</small><b>1,294</b></span><span><small>Locations</small><b>14</b></span></div><div className="review-grid">{[['Melbourne East','120 Collins St, Melbourne','4.9','282'],['Geelong','18 Moorabool St, Geelong','4.8','194']].map(r=><article className="surface location-card" key={r[0]}><header><div><h3>{r[0]}</h3><small><MapPin size={12}/>{r[1]}</small></div><b>{r[2]} <Star size={14}/></b></header><p>{r[3]} reviews</p><div className="rating-bars">{[92,6,2,0,0].map((x,i)=><div key={i}><span>{5-i}★</span><i><b style={{width:`${x}%`}}/></i></div>)}</div><footer><button className="button secondary"><Globe2 size={14}/>View on Google</button><button className="button secondary"><CopyIcon/>Copy review link</button></footer></article>)}</div></Shell>}
function CopyIcon(){return <span style={{fontSize:12}}>⧉</span>}
