'use client';
import {useMemo,useState} from 'react';
import {Copy,ExternalLink,Filter,Plus,RefreshCw,Search,Settings2,ChevronRight} from 'lucide-react';
import {enquiries,inspections} from '../lib/data';
const titles={enquiries:'Enquiries',inspections:'Inspections',inspectors:'Inspectors',franchises:'Franchises',storage:'Storage',campaigns:'Campaigns',referrals:'Referrals',reviews:'Reviews / Locations','quick-sms':'Quick SMS'};
const copy=t=>navigator.clipboard?.writeText(t);
export default function RecordsModule({module,slug=[]}){
 const [q,setQ]=useState(''),[selected,setSelected]=useState(null);const title=titles[module]||module;const variant=slug.join(' · ');
 const rows=useMemo(()=>module==='enquiries'?enquiries:module==='inspections'?inspections:[
  {id:'01',name:module==='inspectors'?'Dimitrios Moutsos':module==='franchises'?'Melbourne East':module==='storage'?'Documents / Contracts':module==='campaigns'?'Winter Property Checklist':module==='referrals'?'Grace Wilson':module==='reviews'?'Melbourne Central':'Operational record',address:'Current network scope',status:module==='campaigns'?'Sent':'Active',type:title,franchise:'Head Office',time:'Updated today'}
 ].filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[module,q]);
 return <div className="stack-lg"><div className="page-heading"><div><p className="eyebrow">{variant||'Operations'}</p><h1>{title}</h1><p>Scoped records with compact actions and accessible detail views.</p></div><div className="heading-actions"><button className="button secondary"><RefreshCw size={15}/>Refresh</button><button className="button primary" onClick={()=>setSelected({name:`New ${title.slice(0,-1)||title}`,status:'Draft'})}><Plus size={15}/>Add {title.replace(/s$/,'')}</button></div></div>
 <section className="surface toolbar"><label className="search-field"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${title.toLowerCase()}`}/></label><button className="button secondary"><Filter size={15}/>Filters</button><button className="button secondary"><Settings2 size={15}/>Columns</button><span className="result-count">{rows.length} records</span></section>
 <section className="surface record-table"><div className="record-head"><span>Record</span><span>Type / source</span><span>Status</span><span>Scope</span><span></span></div>{rows.map(r=><button type="button" className="record-row" key={r.id} onClick={()=>setSelected(r)}><span><b>{r.name}</b><small>{r.address||r.email||r.id}</small></span><span><b>{r.type||title}</b><small>{r.channel||r.time||'Operational record'}</small></span><span><em className={`status ${(r.status||'Active').toLowerCase().replaceAll(' ','-')}`}>{r.status||'Active'}</em></span><span><b>{r.franchise||'All Franchises'}</b><small>{r.inspector||'Network scope'}</small></span><ChevronRight size={16}/></button>)}</section>
 {selected&&<div className="side-sheet-layer" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="detail-sheet"><header><div><small>{title}</small><h2>{selected.name}</h2></div><button onClick={()=>setSelected(null)}>×</button></header><div className="detail-body"><div className="detail-grid"><span><small>Status</small><b>{selected.status||'Active'}</b></span><span><small>Franchise</small><b>{selected.franchise||'Head Office'}</b></span><span><small>Reference</small><b>{selected.id}</b></span><span><small>Updated</small><b>{selected.time||'Today'}</b></span></div><div className="detail-block"><small>Address / description</small><p>{selected.address||'Operational record for the current network scope.'}</p></div><div className="detail-actions"><button className="button secondary" onClick={()=>copy(selected.id)}><Copy size={14}/>Copy reference</button><button className="button secondary"><ExternalLink size={14}/>Open related</button><button className="button primary">Edit record</button></div></div></aside></div>}
 </div>
}
