'use client';
import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,ExternalLink,MessageSquareText,Share2,ShieldCheck} from 'lucide-react';
import {reportSections} from '../lib/data';
const templates={executive:{label:'Executive',desc:'Client-first summary with strong visual hierarchy.'},technical:{label:'Technical',desc:'Dense evidence and compliance-oriented detail.'},editorial:{label:'Editorial',desc:'Premium narrative presentation with calmer pacing.'},compact:{label:'Compact',desc:'Reduced page count for fast review and sharing.'}};
export default function ReportStudio(){
 const [template,setTemplate]=useState('executive'),[section,setSection]=useState(1),[outline,setOutline]=useState(220),[qa,setQa]=useState(null);const drag=useRef(false);
 useEffect(()=>{const move=e=>{if(drag.current)setOutline(Math.max(180,Math.min(340,e.clientX-240)))};const up=()=>drag.current=false;addEventListener('pointermove',move);addEventListener('pointerup',up);return()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up)}},[]);
 const preview=`/reports/IF-20841/preview?template=${template}`;
 async function share(){if(navigator.share)await navigator.share({title:'InspectFlow report',url:location.origin+preview});else{await navigator.clipboard.writeText(location.origin+preview);alert('Report link copied')}}
 function runQA(){setQa({score:96,items:['All mandatory sections completed','Major finding has photo evidence','Timber-pest summary approved','Inspector sign-off present']})}
 return <div className="report-studio-page"><div className="page-heading"><div><p className="eyebrow">IF-20841 · Michael Matthey</p><h1>Report Studio</h1><p>Issue-ready report composition, QA and client sharing.</p></div><div className="heading-actions"><button className="button secondary" onClick={runQA}><ShieldCheck size={15}/>Run QA</button><button className="button secondary" onClick={()=>dispatchEvent(new CustomEvent('inspectflow:open-agent',{detail:{prompt:'Review IF-20841 and tell me what still needs attention before issue.'}}))}><MessageSquareText size={15}/>Ask Agent</button><button className="button secondary" onClick={share}><Share2 size={15}/>Share</button><a className="button primary" href={preview} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Open Preview</a></div></div>
 <section className="studio-toolbar surface"><div><label>Template<select value={template} onChange={e=>setTemplate(e.target.value)}>{Object.entries(templates).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><span>{templates[template].desc}</span></div><div className="studio-meta"><span><small>Readiness</small><b>96%</b></span><span><small>Pages</small><b>{template==='compact'?31:57}</b></span><span><small>Findings</small><b>8</b></span></div></section>
 {qa&&<section className="qa-strip"><CheckCircle2 size={17}/><div><b>Report readiness {qa.score}%</b><span>{qa.items.join(' · ')}</span></div></section>}
 <section className="report-workspace surface" style={{gridTemplateColumns:`${outline}px 6px minmax(0,1fr)`}}><aside className="report-outline"><header><strong>Report sections</strong><small>19 client-facing sections</small></header>{reportSections.map((s,i)=><button type="button" className={section===i?'active':''} key={s} onClick={()=>setSection(i)}><span>{String(i+1).padStart(2,'0')}</span>{s}</button>)}</aside><div className="splitter" role="separator" aria-label="Resize report outline" aria-orientation="vertical" onPointerDown={()=>drag.current=true}/><div className="report-canvas"><div className={`report-sheet template-${template}`}><header className="report-brand"><span>IF</span><div><b>InspectFlow</b><small>Building Inspections</small></div><em>Client report</em></header><div className="report-hero"><div className="property-photo"><div className="photo-sky"/><div className="photo-house"/></div><div className="hero-copy"><small>IF-20841</small><h2>Building &amp; Pest<br/>Inspection Report</h2><p>51 Trisha Drive, Rowville VIC 3178</p></div></div><div className="report-summary-grid"><span><small>Inspection</small><b>2026-07-23 · 09:00</b></span><span><small>Client</small><b>Michael Matthey</b></span><span><small>Inspector</small><b>Dimitrios Moutsos</b></span><span><small>Report type</small><b>Building &amp; Pest Inspection</b></span></div><section className="report-content"><p className="report-kicker">{String(section+1).padStart(2,'0')} · {reportSections[section]}</p><h3>{section===1?'Decision-critical findings':reportSections[section]}</h3><p>The inspected property is generally consistent with a dwelling of similar age and construction. Findings are documented with evidence, access limitations and recommended next actions.</p><div className="finding-metrics"><span><b>48</b><small>Visually fine</small></span><span><b>7</b><small>Minor findings</small></span><span><b>1</b><small>Major finding</small></span></div><div className="finding-card"><div className="evidence-placeholder">Evidence 04</div><div><small>Kitchen A · Benchtop</small><b>Small chip to laminate edge beside the sink.</b><p>Monitor and seal to prevent moisture ingress.</p><em>General Advice / Minor Defect</em></div></div></section><footer><span>InspectFlow · IF-20841</span><span>Page {section+1} of 57</span></footer></div></div></section>
 </div>
}
