import {reportSections} from '../lib/data';

export const REPORT_TEMPLATES={
 executive:{label:'Executive',desc:'Client-first decision summary with a calm property-led cover.',pages:42,tone:'Forest / Sand'},
 technical:{label:'Technical',desc:'Evidence-dense inspection record with compliance tables and metadata rails.',pages:61,tone:'Blueprint / Ice'},
 editorial:{label:'Editorial',desc:'Premium narrative report with image-led pages and generous editorial hierarchy.',pages:48,tone:'Clay / Parchment'},
 compact:{label:'Compact',desc:'Condensed field-to-client report optimized for fast reading and printing.',pages:30,tone:'Graphite / Mint'}
};

const meta={id:'IF-20841',property:'51 Trisha Drive, Rowville VIC 3178',inspection:'23 Jul 2026 · 09:00',client:'Michael Matthey',inspector:'Dimitrios Moutsos',type:'Building & Pest Inspection'};
const findings=[
 {area:'Kitchen',element:'Benchtop',condition:'Minor defect',note:'Small chip to laminate edge beside the sink.',action:'Seal the exposed edge and monitor for moisture ingress.',photo:'Evidence 04'},
 {area:'Hallways',element:'Walls',condition:'General advice',note:'Minor surface cracking visible at the hallway junction.',action:'Monitor for movement and repair finishes during routine maintenance.',photo:'Evidence 11'},
 {area:'Roof Areas',element:'Access',condition:'Access limitation',note:'A portion of the roof void was not safely accessible at inspection.',action:'Arrange safe access if further invasive assessment is required.',photo:'Evidence 26'}
];

const sectionCopy={
 'Executive Summary':'The inspected property is generally consistent with a dwelling of similar age and construction. No major structural defect is recorded in this sample report. Maintenance items, access limitations and timber-pest risk conditions are summarised below for clear client action.',
 'Property Description':'Detached residential dwelling of brick and timber construction with tiled roof covering. The report records the visually accessible areas and the limitations present on the inspection date.',
 'Definitions':'Condition ratings distinguish visually fine items, general advice or minor defects, major defects, areas unable to be inspected and items that are not applicable.',
 'Inspection Agreement':'The inspection is a visual, non-invasive assessment of accessible areas. It should be read with the definitions, access limitations and terms contained in this report.',
 'Terms & Conditions':'This report is prepared for the named client for the stated property and inspection date. Recommendations for specialist assessment remain subject to the relevant qualified trade or consultant.',
 'Hallways':'Hallway surfaces were generally serviceable. Minor finish cracking was observed and recorded as a maintenance item rather than a structural defect.',
 'Kitchen':'Kitchen fixtures and finishes were generally serviceable. A small chip to the benchtop laminate edge was recorded with a maintenance recommendation.',
 'Laundry':'Laundry surfaces, fixtures and visible plumbing connections were inspected where accessible. No significant visual defect was recorded in the accessible areas.',
 'Bedrooms':'Accessible bedroom floors, walls, ceilings, windows and doors were inspected. Minor wear consistent with age was noted where applicable.',
 'Bathrooms':'Accessible bathroom surfaces, fixtures, ventilation and visible seals were reviewed. Ongoing seal maintenance is recommended in wet areas.',
 'Ensuite':'The ensuite was visually inspected for accessible finishes, fixtures, ventilation and moisture-related indicators. Routine maintenance applies.',
 'Exterior':'Accessible external walls, openings, drainage interfaces and visible finishes were reviewed from ground-accessible positions.',
 'Roof Areas':'Roof observations were limited to safely accessible areas. The recorded access limitation should be considered if further assessment is required.',
 'Sub-floor':'Accessible sub-floor areas were inspected where safe entry and clearance permitted. Obstructions and access restrictions are recorded where relevant.',
 'Timber Pest':'No active timber-pest evidence is recorded in the accessible sample areas. Conditions conducive to timber-pest activity should still be managed through moisture, drainage and vegetation maintenance.',
 'Findings Summary':'The priority is routine maintenance, monitoring of minor finish movement, management of access limitations and continued timber-pest risk reduction. No major structural defect is recorded in this sample summary.',
 'Inspector Sign-off':'The report has been reviewed for completeness, evidence linkage, access limitations and client-facing recommendations before issue.'
};

function Placeholder({label='Property overview image',className=''}){return <div className={`rt-image-placeholder ${className}`} role="img" aria-label={label}><span>{label}</span><small>Image placeholder · replace with inspection media</small></div>}
function SummaryMetrics({dense=false}){return <div className={`rt-summary-metrics ${dense?'dense':''}`}><span><b>48</b><small>Visually fine</small></span><span><b>7</b><small>Advice / minor</small></span><span><b>0</b><small>Major structural</small></span></div>}
function Findings({compact=false}){return <div className={`rt-findings ${compact?'compact':''}`}>{findings.map((f,index)=><article key={`${f.area}-${f.element}`}><Placeholder label={f.photo} className="rt-evidence-thumb"/><div><small>{String(index+1).padStart(2,'0')} · {f.area} / {f.element}</small><h4>{f.note}</h4><p>{f.action}</p><em>{f.condition}</em></div></article>)}</div>}
function MetaGrid({compact=false}){return <div className={`rt-meta-grid ${compact?'compact':''}`}><span><small>Inspection</small><b>{meta.inspection}</b></span><span><small>Client</small><b>{meta.client}</b></span><span><small>Inspector</small><b>{meta.inspector}</b></span><span><small>Report type</small><b>{meta.type}</b></span></div>}
function SectionTable(){return <div className="rt-condition-table"><div><b>Element</b><b>Condition</b><b>Inspector comment</b></div>{['Floors','Walls','Ceilings','Doors','Windows'].map((item,index)=><div key={item}><span>{item}</span><span>{index===1?'General advice / minor defect':'Visually fine'}</span><span>{index===1?'Minor finish cracking observed. Monitor during routine maintenance.':'No significant visual defect noted in accessible areas.'}</span></div>)}</div>}
function PageFooter({index,total,label}){return <footer className="rt-page-footer"><span>{meta.id} · {label}</span><span>{index} / {total}</span></footer>}

function ExecutiveCover(){return <article className="rt-page rt-executive-cover"><header><div className="rt-wordmark"><span>IF</span><div><b>InspectFlow</b><small>Building Inspections</small></div></div><em>Client report</em></header><Placeholder className="rt-cover-photo"/><div className="rt-executive-title"><small>{meta.id}</small><h1>Building &amp; Pest<br/>Inspection Report</h1><p>{meta.property}</p></div><MetaGrid/></article>}
function ExecutiveSection({section,index,total}){const title=reportSections[section];return <article className="rt-page rt-executive-page"><div className="rt-section-number">{String(section+1).padStart(2,'0')}</div><header><p>{title}</p><h2>{section===1?'Decision-ready property summary':title}</h2></header><p className="rt-lead">{sectionCopy[title]||'This section records the visual observations, access limitations, supporting evidence and recommended next actions for the inspected area.'}</p>{section===1?<><SummaryMetrics/><div className="rt-priority-band"><div><small>Priority</small><b>Maintenance and access follow-up</b></div><p>No major structural defect is recorded in this sample summary. Address routine maintenance and any specialist follow-up noted in the detailed sections.</p></div><Findings/></>:<div className="rt-two-column"><div><h3>Observed condition</h3><p>{sectionCopy[title]||'Accessible items were assessed using the report condition framework.'}</p><SectionTable/></div><aside><Placeholder label={`${title} overview`}/><h3>Recommendations</h3><p>Maintain documented items, monitor changes and obtain specialist advice where the report specifically recommends it.</p></aside></div>}<PageFooter index={index} total={total} label={title}/></article>}

function TechnicalCover(){return <article className="rt-page rt-technical-cover"><aside><div className="rt-tech-mark">IF</div><small>TECHNICAL INSPECTION RECORD</small><b>{meta.id}</b><dl><div><dt>CLIENT</dt><dd>{meta.client}</dd></div><div><dt>INSPECTOR</dt><dd>{meta.inspector}</dd></div><div><dt>DATE</dt><dd>{meta.inspection}</dd></div></dl></aside><main><div className="rt-tech-grid-bg"/><div className="rt-tech-heading"><small>BUILDING / TIMBER PEST</small><h1>Inspection<br/>Record</h1><p>{meta.property}</p></div><Placeholder label="Primary property evidence" className="rt-tech-photo"/><div className="rt-tech-cover-index"><span>19 sections</span><span>55 checklist items</span><span>Evidence linked</span></div></main></article>}
function TechnicalSection({section,index,total}){const title=reportSections[section];return <article className="rt-page rt-technical-page"><header><div><small>{meta.id} / SECTION {String(section+1).padStart(2,'0')}</small><h2>{title}</h2></div><span className="rt-tech-status">Reviewed</span></header><div className="rt-tech-layout"><aside><dl><div><dt>Property</dt><dd>{meta.property}</dd></div><div><dt>Inspection</dt><dd>{meta.inspection}</dd></div><div><dt>Inspector</dt><dd>{meta.inspector}</dd></div><div><dt>Classification</dt><dd>Visual / non-invasive</dd></div></dl><Placeholder label={`${title} evidence`} className="rt-tech-side-photo"/></aside><main><div className="rt-tech-note"><b>Section narrative</b><p>{sectionCopy[title]||'Accessible elements were inspected visually and classified under the report condition framework.'}</p></div>{section===1?<><SummaryMetrics dense/><Findings compact/></>:<><SectionTable/><div className="rt-tech-evidence-grid"><Placeholder label="Evidence A"/><Placeholder label="Evidence B"/><Placeholder label="Evidence C"/></div></>}</main></div><PageFooter index={index} total={total} label={title}/></article>}

function EditorialCover(){return <article className="rt-page rt-editorial-cover"><div className="rt-editorial-photo"><Placeholder label="Full property hero image"/></div><div className="rt-editorial-copy"><span className="rt-editorial-issue">{meta.id}</span><p>INSPECTION REPORT / JULY 2026</p><h1>Building &amp;<br/><i>Pest Inspection</i></h1><div className="rt-editorial-rule"/><p className="rt-editorial-address">{meta.property}</p><MetaGrid compact/></div></article>}
function EditorialSection({section,index,total}){const title=reportSections[section];return <article className="rt-page rt-editorial-page"><header><span>{String(section+1).padStart(2,'0')}</span><div><p>INSPECTFLOW / CLIENT REPORT</p><h2>{title}</h2></div></header><div className="rt-editorial-layout"><main><p className="rt-editorial-lead">{sectionCopy[title]||'This section presents the inspector’s observations, evidence and recommended next actions in a client-readable format.'}</p>{section===1?<><blockquote>“The property is generally consistent with a dwelling of similar age and construction, with maintenance and access items clearly identified for follow-up.”</blockquote><SummaryMetrics/><Findings compact/></>:<><h3>What we observed</h3><p>{sectionCopy[title]||'Accessible observations and supporting evidence are recorded for this section.'}</p><Findings compact/></>}</main><aside><Placeholder label={`${title} feature image`}/><div className="rt-editorial-note"><small>CLIENT NOTE</small><p>Read this section together with access limitations and any trade-specific recommendations.</p></div></aside></div><PageFooter index={index} total={total} label={title}/></article>}

function CompactCover(){return <article className="rt-page rt-compact-cover"><header><div className="rt-wordmark"><span>IF</span><div><b>InspectFlow</b><small>Inspection report</small></div></div><b>{meta.id}</b></header><div className="rt-compact-title"><small>BUILDING &amp; PEST</small><h1>{meta.property}</h1><p>Concise client report · {meta.inspection}</p></div><div className="rt-compact-cover-grid"><MetaGrid compact/><Placeholder label="Property image"/></div><SummaryMetrics dense/><div className="rt-compact-summary"><b>Summary</b><p>No major structural defect is recorded in this sample report. Seven maintenance or advisory findings require routine follow-up.</p></div></article>}
function CompactSection({section,index,total}){const title=reportSections[section];return <article className="rt-page rt-compact-page"><header><div><small>{String(section+1).padStart(2,'0')}</small><h2>{title}</h2></div><span>{meta.id}</span></header><div className="rt-compact-section-grid"><main><p>{sectionCopy[title]||'Accessible items were visually assessed and recorded using the report condition framework.'}</p><SectionTable/></main><aside><Placeholder label={`${title} evidence`}/><div className="rt-compact-callout"><b>Next action</b><p>Maintain, monitor and obtain specialist advice only where explicitly recommended.</p></div></aside></div><PageFooter index={index} total={total} label={title}/></article>}

function TemplatePage({template,section,index,total}){
 if(section===0){if(template==='technical')return <TechnicalCover/>;if(template==='editorial')return <EditorialCover/>;if(template==='compact')return <CompactCover/>;return <ExecutiveCover/>}
 if(template==='technical')return <TechnicalSection section={section} index={index} total={total}/>;
 if(template==='editorial')return <EditorialSection section={section} index={index} total={total}/>;
 if(template==='compact')return <CompactSection section={section} index={index} total={total}/>;
 return <ExecutiveSection section={section} index={index} total={total}/>;
}

export default function ReportTemplate({template='executive',activeSection=1,mode='studio'}){
 const safeTemplate=REPORT_TEMPLATES[template]?template:'executive';
 const total=REPORT_TEMPLATES[safeTemplate].pages;
 const sections=reportSections.map((_,index)=>index);
 return <div className={`report-template report-template-${safeTemplate} ${mode==='document'?'is-document':'is-studio'}`} data-active-section={activeSection}>{sections.map((section,index)=><div className={`rt-section-anchor ${activeSection===section?'is-active':''}`} data-report-section={section} id={`report-section-${section}`} key={`${safeTemplate}-${section}`}><TemplatePage template={safeTemplate} section={section} index={index+1} total={total}/></div>)}</div>
}
