export const franchises=['All Franchises','Ballarat','Bendigo','Geelong','Melbourne East','Mornington Peninsula'];
export const enquiries=[
{id:'E-4812',segment:'HeadOffice',confirmed:true,stage:'Access & Booking Confirmed',notes:'Agent access confirmed. Report produced after inspection.',name:'Michael Matthey',phone:'0412 555 014',email:'michael@example.com',address:'51 Trisha Drive, Rowville VIC 3178',type:'Building & Pest Inspection',price:890,status:'Booked',franchise:'Melbourne East',channel:'Online Booking',time:'Today · 10:42'},
{id:'E-4813',segment:'HeadOffice',confirmed:false,stage:'Access Requested',notes:'Client asked for access update before booking.',name:'Olivia Hart',phone:'0438 221 904',email:'olivia@example.com',address:'18 Peterhead Road, Glen Waverley VIC 3150',type:'Pre-Purchase Building Inspection',price:720,status:'Follow Up',franchise:'Melbourne East',channel:'Phone',time:'Today · 09:18'},
{id:'E-4814',segment:'Franchise',confirmed:false,stage:'Enquiry Received',notes:'New franchise-attributed lead from Google Chat.',name:'Noah Wilson',phone:'0407 772 219',email:'noah@example.com',address:'4 Lakeshore Avenue, Berwick VIC 3806',type:'Pool Barrier Inspection',price:430,status:'New',franchise:'Mornington Peninsula',channel:'Google Chat',time:'Yesterday · 16:04'}
];
export const inspections=[
{id:'IF-20841',name:'Michael Matthey',date:'29 Jul 2026',time:'09:00',price:890,paid:890,address:'51 Trisha Drive, Rowville VIC 3178',status:'Report Ready',type:'Building & Pest Inspection',inspector:'Dimitrios Moutsos',franchise:'Melbourne East',report:'Submitted'},
{id:'IF-20902',name:'Ava Roberts',date:'29 Jul 2026',time:'10:30',price:720,paid:200,address:'9 Redwood Lane, Bendigo VIC',status:'Inspection Pending',type:'Pre-Purchase Building Inspection',inspector:'Jordan Lee',franchise:'Bendigo',report:'Draft'},
{id:'IF-P-20911',name:'Oliver Singh',date:'30 Jul 2026',time:'13:15',price:430,paid:430,address:'22 Seaview Drive, Frankston VIC',status:'Inspection Pending',type:'Swimming Pool/Spa Safety Barrier Inspection',inspector:'Priya Nair',franchise:'Mornington Peninsula',report:'Draft'}
];
export const reportSections=['Cover','Executive Summary','Contents','Property Description','Definitions','Inspection Agreement','Terms & Conditions','Hallways','Kitchen','Laundry','Bedrooms','Bathrooms','Ensuite','Exterior','Roof Areas','Sub-floor','Timber Pest','Findings Summary','Inspector Sign-off'];
